### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by shundroid**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/onigo-port/2)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[eventPublisher.ts, line 1 at r1](https://reviewable.io:443/reviews/comozilla/onigo-port/2#-KbtjjOnqAc1JMAWXp8X:-KbtjjOnqAc1JMAWXp8Y:bdru9b5) ([raw file](https://github.com/comozilla/onigo-port/blob/b85a7371b284aa4e78501624a0a9d14bb521610a/eventPublisher.ts#L1)):*
> ```XML
> export type observer = (...eventData) => void;
> ```

observer って直訳すると監視者になるすよね。
一方でこれは関数ですよね。
名前的には observeFunction とかになるのかなぁ。
observer(...data) のように呼び出すのは何か違和感がございます。

---

*[components/socketManager.ts, line 26 at r1](https://reviewable.io:443/reviews/comozilla/onigo-port/2#-Kbti8klEBARwExLrvqn:-Kbti8km32fAnDJC54WR:b-4ix22d) ([raw file](https://github.com/comozilla/onigo-port/blob/b85a7371b284aa4e78501624a0a9d14bb521610a/components/socketManager.ts#L26)):*
> ```XML
>   private io: SocketIO.Server;
>   constructor(port: number) {
>     super();
> ```

この super は必要なのかしら？
ComponentBase にはコンストラクタもございませんし。

---

*[components/spheroManager.ts, line 8 at r1](https://reviewable.io:443/reviews/comozilla/onigo-port/2#-KbtjZpsAhPH-cUDc4bZ:-KbtjZpsAhPH-cUDc4b_:bhrgxoj) ([raw file](https://github.com/comozilla/onigo-port/blob/b85a7371b284aa4e78501624a0a9d14bb521610a/components/spheroManager.ts#L8)):*
> ```XML
>   orbs: { [key: string]: Orb };
>   constructor() {
>     super();
> ```

ここもいらない？

---

*[components/spheroManager.ts, line 21 at r1](https://reviewable.io:443/reviews/comozilla/onigo-port/2#-Kbtj60RS9cujt0Gtzbj:-Kbtj60SDa8Cmx5TrQZo:bgiuiii) ([raw file](https://github.com/comozilla/onigo-port/blob/b85a7371b284aa4e78501624a0a9d14bb521610a/components/spheroManager.ts#L21)):*
> ```XML
>     const orb = sphero(port);
>     orb.connect(error => {
>       this.orbs[name] = new Orb(name, port, orb);
> ```

ここの error ハンドリングはしないです？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-port/2)*

**Comment by shundroid** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[eventPublisher.ts, line 1 at r1](https://reviewable.io:443/reviews/comozilla/onigo-port/2#-KbtjjOnqAc1JMAWXp8X:-Kbvu98rXmvQdQgQ0aUW:b-glrnyz) ([raw file](https://github.com/comozilla/onigo-port/blob/b85a7371b284aa4e78501624a0a9d14bb521610a/eventPublisher.ts#L1)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

observer って直訳すると監視者になるすよね。
一方でこれは関数ですよね。
名前的には observeFunction とかになるのかなぁ。
observer(...data) のように呼び出すのは何か違和感がございます。
</blockquote></details>

わかりました、そうします

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-port/2)*

**Comment by shundroid** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/socketManager.ts, line 26 at r1](https://reviewable.io:443/reviews/comozilla/onigo-port/2#-Kbti8klEBARwExLrvqn:-KbxswF5IEI9U4uKVMiC:b-damjh4) ([raw file](https://github.com/comozilla/onigo-port/blob/b85a7371b284aa4e78501624a0a9d14bb521610a/components/socketManager.ts#L26)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

この super は必要なのかしら？
ComponentBase にはコンストラクタもございませんし。
</blockquote></details>

typescript だとないとエラーが出てしまうんです・・・

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-port/2)*

**Comment by shundroid** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/spheroManager.ts, line 8 at r1](https://reviewable.io:443/reviews/comozilla/onigo-port/2#-KbtjZpsAhPH-cUDc4bZ:-KbxszVCKNqEEzgHG5SY:biqpxre) ([raw file](https://github.com/comozilla/onigo-port/blob/b85a7371b284aa4e78501624a0a9d14bb521610a/components/spheroManager.ts#L8)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

ここもいらない？
</blockquote></details>

ここもないとエラーが出てしまいます・・

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-port/2)*

**Comment by shundroid** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/spheroManager.ts, line 21 at r1](https://reviewable.io:443/reviews/comozilla/onigo-port/2#-Kbtj60RS9cujt0Gtzbj:-Kbxt27iuiG1jWZWZTMO:bhgfx5g) ([raw file](https://github.com/comozilla/onigo-port/blob/b85a7371b284aa4e78501624a0a9d14bb521610a/components/spheroManager.ts#L21)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

ここの error ハンドリングはしないです？
</blockquote></details>

します！

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-port/2)*

**Comment by dadaa** [comment]
Reviewed 6 of 9 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/onigo-port/2)*

**Pull request merged**
